#!/usr/bin/env python3
"""sources_to_list - convert local CSV "sources" into a Soulseek source list.

Reads one or more CSV sources (files or directories) and emits a single
Soulseek list file. Two modes:

  csv-ref (default)  Each CSV source is emitted as one line referencing the
                     file path; Soulseek resolves the whole CSV as song/album
                     jobs when it processes the list.

  search             Each CSV row is turned into a search string line:
                     "Artist - Title" for song rows, "Artist - Album" for
                     album rows (mirrors Soulseek's string shorthand, album by
                     default, song rows tagged with --song search mode when
                     using the --song flag).

The script is fully offline (stdlib only): it reads local CSV files and
writes a text list. It performs no network access and no Soulseek activity.
"""

from __future__ import annotations

import argparse
import csv
import os
import sys

SELF = os.path.dirname(os.path.realpath(__file__))
REPO = os.path.dirname(SELF)
PROG = "sources_to_list"


def header_col(header, alias_set, requested=None):
    for h in header:
        if requested is not None:
            if h.lower() == requested.lower():
                return h
        elif h.lower() in alias_set:
            return h
    return None


def discover_sources(paths):
    sources = []
    for p in paths:
        if os.path.isdir(p):
            for entry in sorted(os.listdir(p)):
                child = os.path.join(p, entry)
                if child.lower().endswith(".csv") and os.path.isfile(child):
                    sources.append(child)
        elif os.path.isfile(p):
            sources.append(p)
        else:
            print(f"{PROG}: source not found: {p}", file=sys.stderr)
            sys.exit(2)
    if not sources:
        print(f"{PROG}: no CSV sources found", file=sys.stderr)
        sys.exit(2)
    return sources


def rel(path):
    try:
        r = os.path.relpath(path, REPO)
    except ValueError:
        r = path
    return r if not r.startswith("..") else path


def search_lines(path):
    lines = []
    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.reader(fh)
        try:
            header = [h.strip() for h in next(reader)]
        except StopIteration:
            return lines
        i_artist = header_col(header, {"artist", "artists", "performer"}, None)
        i_title = header_col(header, {"title", "track", "track title", "song", "song title", "name"}, None)
        i_album = header_col(header, {"album", "release"}, None)
        idx = {c: i for i, c in enumerate(header) if c}
        for row in reader:
            artist = row[idx[i_artist]] if i_artist and i_artist in idx else ""
            title = row[idx[i_title]] if i_title and i_title in idx else ""
            album = row[idx[i_album]] if i_album and i_album in idx else ""
            artist, title, album = (v.strip() for v in (artist, title, album))
            if title:
                lines.append(f"{artist} - {title}" if artist else title)
            elif album:
                lines.append(f"{artist} - {album}" if artist else album)
    return lines


def emit(name, header, lines):
    with open(name, "w", encoding="utf-8") as fh:
        fh.write(f"# {header}\n")
        fh.write("# Generated by sources_to_list.py - source list for Soulseek.\n")
        fh.write("# One source per line; '#' and blank lines are ignored.\n\n")
        for line in lines:
            fh.write(line.rstrip("\n") + "\n")
    return len(lines)


def main(argv=None):
    ap = argparse.ArgumentParser(prog=PROG, description=__doc__)
    ap.add_argument("sources", nargs="+", help="CSV file(s) and/or directories to convert")
    ap.add_argument("-o", "--out", help="output list file (default: lists/sources.list)")
    ap.add_argument("-m", "--mode", choices=["csv-ref", "search"], default="csv-ref",
                    help="emit CSV path references (csv-ref) or per-row search strings (search)")
    ap.add_argument("-s", "--song", action="store_true",
                    help="song mode for search strings (only relevant with --mode search)")
    args = ap.parse_args(argv)

    out = args.out or os.path.join("lists", "sources.list")
    sources = discover_sources(args.sources)
    lines = []
    for src in sources:
        if args.mode == "csv-ref":
            lines.append(rel(src))
        else:
            lines.extend(search_lines(src))

    if not lines:
        print(f"{PROG}: no lines generated", file=sys.stderr)
        return 2

    n = emit(out, "Soulseek source list", lines)
    print(f"{PROG}: wrote {n} line(s) to {out} (mode={args.mode}, offline)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())